from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import os
import re
import tempfile

from . import LANGUAGE_VERSION
from .ast_nodes import Program
from .backend_c import generate_c, validate_shader_name
from .diagnostics import ShaderCompilerError, SourceFile
from .fingerprint import build_fingerprint, compiler_fingerprint, sha256_bytes
from .ir import IRModule
from .lexer import Lexer
from .lower import Lowerer
from .optimizer import optimize
from .parser import Parser
from .semantic import SemanticAnalyzer
from .tokens import Token


_BUILD_HASH_PATTERN = re.compile(r"^ \* Build SHA-256:\s+([0-9a-f]{64})$", re.MULTILINE)


@dataclass(frozen=True)
class CompilerOptions:
    def fingerprint_data(self) -> dict[str, object]:
        return {}


@dataclass
class CompilationResult:
    source: SourceFile
    tokens: list[Token]
    ast: Program
    ir: IRModule
    c_text: str
    h_text: str
    source_hash: str
    compiler_hash: str
    build_hash: str


@dataclass(frozen=True)
class ProjectCompileSummary:
    compiled: int
    cached: int


def compile_project(project_root: Path, options: CompilerOptions | None = None) -> ProjectCompileSummary:
    project_root = project_root.resolve()
    options = options or CompilerOptions()
    shader_dir = project_root / "shaders"
    shaderc_dir = project_root / "tools" / "shaderc"
    shader_dir.mkdir(parents=True, exist_ok=True)

    compiler_hash = compiler_fingerprint(shaderc_dir)
    sources = sorted(shader_dir.glob("*.grsh"), key=lambda path: path.name)

    print("GRAPE Shader Compiler")
    compiled = 0
    cached = 0

    for source_path in sources:
        shader_name = source_path.stem
        try:
            validate_shader_name(shader_name)
        except ValueError as error:
            raise RuntimeError(f"{source_path.as_posix()}: error: {error}") from error

        relative_source = source_path.relative_to(project_root).as_posix()
        source_bytes = source_path.read_bytes()
        source_hash = sha256_bytes(source_bytes)
        expected_build_hash = build_fingerprint(
            relative_source,
            source_bytes,
            compiler_hash,
            LANGUAGE_VERSION,
            options.fingerprint_data(),
        )

        c_path = shader_dir / f"generated_{shader_name}.c"
        h_path = shader_dir / f"generated_{shader_name}.h"

        if _cache_matches(c_path, h_path, expected_build_hash):
            print(f"  {source_path.name:<24} up to date")
            cached += 1
            continue

        print(f"  {source_path.name:<24} compiling...")
        result = compile_shader(
            project_root,
            source_path,
            compiler_hash=compiler_hash,
            options=options,
        )
        _atomic_write(c_path, result.c_text)
        _atomic_write(h_path, result.h_text)
        compiled += 1

    print(f"\n{compiled} compiled, {cached} cached")
    return ProjectCompileSummary(compiled, cached)


def compile_shader(
    project_root: Path,
    source_path: Path,
    *,
    compiler_hash: str | None = None,
    options: CompilerOptions | None = None,
) -> CompilationResult:
    project_root = project_root.resolve()
    source_path = source_path.resolve()
    options = options or CompilerOptions()
    shaderc_dir = project_root / "tools" / "shaderc"
    compiler_hash = compiler_hash or compiler_fingerprint(shaderc_dir)

    relative_source = source_path.relative_to(project_root).as_posix()
    source_bytes = source_path.read_bytes()
    try:
        source_text = source_bytes.decode("utf-8")
    except UnicodeDecodeError as error:
        raise RuntimeError(f"{relative_source}: error: shader source must be UTF-8") from error

    source = SourceFile(Path(relative_source), source_text)
    tokens = Lexer(source).tokenize()
    ast = Parser(source, tokens).parse()
    SemanticAnalyzer(source).analyze(ast)
    ir = optimize(Lowerer(ast).lower())

    source_hash = sha256_bytes(source_bytes)
    build_hash = build_fingerprint(
        relative_source,
        source_bytes,
        compiler_hash,
        LANGUAGE_VERSION,
        options.fingerprint_data(),
    )
    banner = _generated_banner(relative_source, source_hash, compiler_hash, build_hash)
    c_text, h_text = generate_c(ir, source_path.stem, banner)

    return CompilationResult(
        source=source,
        tokens=tokens,
        ast=ast,
        ir=ir,
        c_text=c_text,
        h_text=h_text,
        source_hash=source_hash,
        compiler_hash=compiler_hash,
        build_hash=build_hash,
    )


def _generated_banner(source: str, source_hash: str, compiler_hash: str, build_hash: str) -> str:
    return "\n".join(
        [
            "/*",
            " * AUTO-GENERATED BY GRAPE SHADERC - DO NOT EDIT",
            " *",
            f" * Source:          {source}",
            f" * Shader language: {LANGUAGE_VERSION}",
            f" * Source SHA-256:  {source_hash}",
            f" * Compiler SHA-256: {compiler_hash}",
            f" * Build SHA-256:   {build_hash}",
            " */",
        ]
    )


def _cache_matches(c_path: Path, h_path: Path, build_hash: str) -> bool:
    return _file_build_hash(c_path) == build_hash and _file_build_hash(h_path) == build_hash


def _file_build_hash(path: Path) -> str | None:
    try:
        prefix = path.read_text(encoding="utf-8")[:2048]
    except (OSError, UnicodeDecodeError):
        return None
    match = _BUILD_HASH_PATTERN.search(prefix)
    return match.group(1) if match else None


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    data = text.encode("utf-8")
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as file:
            file.write(data)
        os.replace(temp_name, path)
    except Exception:
        try:
            os.unlink(temp_name)
        except OSError:
            pass
        raise
